### ISSUE TITLE
Replace login text

### ISSUE THREAD

**Issue by w3st3ry** [bnjjj/my-infra#16]
According to the customer area, replace `Login` text by `Identifiant client` to clarify the input. (or can use email address to log in).

**Comment by bnjjj** [comment]
It should be closed with this one #10 which is doing

**Comment by Nokte** [comment]
Sur le login il y a aussi une erreur au mot connexion.

**Comment by bnjjj** [comment]
Done ! Disponible dans la version 1.1.0
