### ISSUE TITLE
Correction intégration

### ISSUE THREAD

**Issue by Nokte** [bnjjj/my-infra#29]
- le texte et l'icon de chargement au pull/refresh est noir, le mettre comme les autres textes
- les icons des widgets ne sont pas centré verticalement
- enlever la border grise du header

**Comment by bnjjj** [comment]
Done pour le premier.
Le 2ème j'ai vérifié c'est centré
Le 3ème j'ai réussi à en retirer une (celle du pull refresh) mais l'autre je ne trouve pas comment faire pour l'instant :)

**Comment by bnjjj** [comment]
Will be fixed in V2
