### ISSUE TITLE
Sort items

### ISSUE THREAD

**Issue by fredt34** [bnjjj/my-infra#45]
I just installed the app on iphone 9 - adding Domains widget, and my 50 domains are here, but unsorted... Quite messy! 
Suggestion: allow sorting by name or extension (.com, .org, .fr...)

Adding other widgets are also unsorted.

**Comment by fredt34** [comment]
Also please add a text box to filter on names!

**Comment by bnjjj** [comment]
Alright, I'm currently doing the v2. The v2 will be more efficient for account with a lot of products (like your 50 domains). Your comment for text box to filter is very interesting. I take care of your advice and add this in v2.0.0

**Comment by bnjjj** [comment]
It will be released in V2 very soon. If you want to get a beta version let me know ASAP :)
