### ISSUE TITLE
Erreur 403

### ISSUE THREAD

**Issue by mafzst** [bnjjj/my-infra#84]
Juste après la connexion, impossible de charger les produits. Dans l'onglet "Assistance" message d'erreur "Bad credentials" 
![2017_04_14_23_07_53](https://cloud.githubusercontent.com/assets/6941014/25056156/57ab5c0c-2167-11e7-9836-c8625fc3ad58.png)

**Comment by bnjjj** [comment]
As-tu essayer de te déconnecter et reconnecter ? Est-ce que tu as la double auth ?

**Comment by mafzst** [comment]
Oui j'ai essayé déco reco 
Oui j'ai la double authentification

**Comment by bnjjj** [comment]
Double authentification par sms ?

**Comment by mafzst** [comment]
Non par OTP

**Comment by bnjjj** [comment]
Ah c'est pour ça, la double auth par OTP est pas encore dispo sur l'app :/

**Comment by mafzst** [comment]
Ok dommage :/
